### PR TITLE
Prism annotations

### PR DESCRIPTION
**Pull request by leftler**
Added annotations for #1.

### CODE REVIEW

**Comment by leftler** [comment]
A lot more annotations could be generated using the Resharper "Annotate!" [internal tool](http://hadihariri.com/2009/06/26/resharpers-hidden-gem/) to add the automatically detectable annotations like `[NotNull]` instances, but I did not want to do that much in a commit.

**Comment by robv8r** [comment]
Thank you very much for your contribution.  I'll review your changes and provide feedback shortly.

**Comment by robv8r** [comment]
Sorry for leaving so many short comments.  That's they way they come across when I comment on the commits directly.  I sincerely appreciate you submitting this pull request.  My feedback is meant as constructive.  Please don't take the number of comments as a negative thing.

**Comment by leftler** [comment]
Don't worry about it, change whatever you need. Once I found out I could just put the XML files I generated in my \packages\Prism.Mvvm.1.0.0\lib\net45 folder and similar I ended up using that.

(Also sorry for taking so long to respond, I don't check my email that GitHub sends to very often.)

**Comment by robv8r** [comment]
pull request manually merged

**Pull request closed without merging**
